### ISSUE TITLE
Define histogram bins with specified domain.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/Webcharts#252]
rather than with extent of data

# Test notes
* Open the [Webcharts config-tester](https://rhoinc.github.io/webcharts-tests/config-tester/test-page/).
  1. Choose _histogram_ in the _Chart Configuration_ dropdown.
  2. Add a custom domain to the _X-axis Settings_: `domain: [0,7]`.
  3. Click the _Render Chart_ button.
  4. Verify that the number of bars in the histogram remains the same.
  5. Choose _histogram-domain_ in the _Webcharts Version_ dropdown.
  6. Verify that the number of bars in the histogram decreases.  This behavior is desired when the domain is explicitly defined in the chart configuration.  Bar widths should be a function of the domain size rather than the range of the data.

**Comment by emmorris** [comment]
https://rhoinc.github.io/webcharts-tests/config-tester/test-page/

Spencer is going to update the config tester so that we can test out this update.  Test notes and config tester updates coming soon.  

Updates that are necessary: point to new data file locations and add safety histogram to drop-down

**Comment by danedexF5** [comment]
Works in Chrome and FF. Spencer opened an issue to fix IE at some point but not critical so approving.
