### ISSUE TITLE
Missing destroy API causes issues in single-page apps.

### ISSUE THREAD

**Issue by rtomsick** [RhoInc/Webcharts#27]
Description
===

When using WebCharts in a single-page app such as one powered by React, the library's behavior coupled with the nature of React causes a bug with rather serious performance implications.

Fixing this will require addition of a destroy/cleanup API to WebCharts Chart object as well as possibly modifications to the D3 library (already done, but AFAIK not upstreamed).

Steps to reproduce
===

0) Create a `Chart` with WebCharts and render it within a React component.
0) Cause the component to unmount (which results in removal of the Chart's target element from the actual DOM.)

Expected outcome
===

Chart unmounts cleanly. No errors produced.

Actual outcome
===

Chart unmounts, however D3 handlers for window resize.  Since the chart no longer exists in the DOM, this causes error spam on the console (as well as a non-zero performance hit.)  Needless to say, for a single-page app that will be potentially rendering and disposing of dozens of charts without a page reload, this is a major issue.

Proposed resolution
===

0) Add a `.destroy()` method to `Chart` to allow callers to signal that the chart will no longer be used (and thus associated resources should be released, handlers unbound, etc.) 

0) If necessary, monkey-patch d3 to support the behavior implemented in [d3 commit 6e3ce48](https://github.com/d3/d3/commit/6e3ce486f8c1bdc3e10000d2921623c32449d5ef).  This allows for a "nuclear option" of just unbinding everything.  (This is what I'm currently using in my application.)

**Comment by jwildfire** [comment]
Thanks for the thorough write-up, @rtomsick . Certainly seems like an issue that would be good to address. Will chat with some of the heavier react users here and see what they think, and then get you an estimate on when we might be able to tackle this. We would of course be happy to collaborate if you wanted to start a pull request.

**Comment by jwildfire** [comment]
cc: @qspencer @evandervrho

**Comment by nbryant** [comment]
Makes complete sense to me and the .destroy() pattern is a common one. Only other thought I have is whether this issue has any implications for https://github.com/RhoInc/react-webchart (which is much more immature anyway)

**Comment by rtomsick** [comment]
> whether this issue has any implications for https://github.com/RhoInc/react-webchart (which is much more immature anyway)

Probably not much, since it doesn't implement componentWillUnmount, which is where the destruction would logically happen. :smile: 

FWIW I kinda lied when I said React, since I'm not using that per se. I'm actually using reagent in a Clojurescript app, so I'm not using React directly.  But I am specifying a componentWillUnmount handler in my chart component anyways, which is where I'm doing the workaround (right now only possible because of my local copy of d3 having the linked patch) of unbinding everything globally.  This is a rather crude solution and requires some additional footwork when I'm rendering multiple chart components with different lifecycles, but it's not too bad.

Still, being able to simply tell the chart to clean up after itself would be much appreciated. Thanks guys!

**Comment by nbryant** [comment]
could probably change this line: https://github.com/RhoInc/Webcharts/blob/master/src/chart/draw.js#L41 to use `window.addEventListener('resize', ...)` and then remove the listener later with `window.removeEventListener`, so we don't have to get d3 involved at all.

**Comment by jwildfire** [comment]
After reading up on destroy methods a bit (([1](http://stackoverflow.com/questions/24821354/how-to-avoid-memory-leaks-using-angularjs-nvd3-directives), [2](https://github.com/d3/d3-selection/blob/master/README.md#handling-events)) it seems like we need to do the following. 

1) Implement Nathan's fix
2) Add support for an onDestroy callback (this may be needed for charts where listeners are created in callbacks)
3) Create a chart.destroy() method that unmounts the chart, runs onDestroy, and deletes the event listeners created by the system. 

I'm hoping to create a branch/pull request to address this before the end of the year.

**Comment by jwildfire** [comment]
The one main remaining gray area for me is surrounding the destroying the `controls` object associated with a chart. Need to figure out if its best to have a separate `controls.destroy()` method (which can maybe be called from `chart.destroy()` as appropriate) or just to deal with controls directly in the `charts.destroy()` method. Thoughts on that one @nbryant?

**Comment by nbryant** [comment]
Seems like we'd want a `controls.destroy()` since controls are created independently from charts. The most straightforward approach would be to require the developer to manually `.destroy()` the controls just as they would a chart.

**Comment by jwildfire** [comment]
Initial implementation of chart.destroy() is ready for review in PR #28. Working example at: http://bl.ocks.org/jwildfire/fd5bb35a6e1a5307b9e0ac83ab4a6384

If this looks ok, I'll create control.destroy() and table.destroy() using the same pattern.

**Comment by rtomsick** [comment]
That will fix our use case.  I assume that a destroyed chart can't be re-used and will have to be reconstructed?

**Comment by jwildfire** [comment]
@rtomsick Generally, yes. You'll want to re-run `myChart = webcharts.createChart()` and then `myChart.init(data)` if you want to re-use a chart after running `myChart.destroy()`

The longer answer is that the `chart` object (the `myChart` object above) isn't actually deleted (aka set to `null`) by the .destroy() method - you need to do that manually. I updated the examples to make that clear. I generally think that is a worthwhile step, since the chart object can be fairly heavy with data and settings bound to it. I can imagine situation where you'd want to keep parts of the chart's metadata around after calling `.destroy()` so we'll leave that up to the user. 

Even though the `myChart` object isn't technically deleted by `chart.destroy()`, I don't recommend re-using the `chart`. Honestly, not even sure how it would work ... the resize functionality will be completely shot, and the data-bindings to the DOM are going to be gone as well.

**Comment by jwildfire** [comment]
I made 2 more commits in the branch to address `controls.destroy()` ([example](http://bl.ocks.org/jwildfire/3cf9dea34afecd477c43db2471df6d6c)) and `tables.destroy()` ([example](http://bl.ocks.org/jwildfire/ff4fa1dbed7ca62e38dbe0d085e9a812)), and both seem to work ok. I also added a `destroyControls` parameter to `chart.destroy()` and set the default to `true`. As a result `chart.destroy()` will attempt to remove controls associated with the chart (if any are found) unless the user specifies otherwise.

I'll see if I can get a code review in the next day or 2, get the details documented in the wiki and then get this released as v1.7.0.

**Comment by rtomsick** [comment]
Yeah, I pretty much figured I'd have to just recreate it.  That's what we're doing now anyways.

The only way that I could see re-init working would be if you rebound all the handlers, etc.  So more of a `detach()` instead of `destroy()`.  But that's a lot of work for no real gain, since in our testing creation isn't that expensive anyways (plus, we can do it offscreen so no biggie even if it were).

Thanks for fixing this!

**Comment by jwildfire** [comment]
I just released [Version 1.7.0](https://github.com/RhoInc/Webcharts/releases/tag/v1.7.0). Let us know if you run in to any issues.
